# Generated by Django 4.2.3 on 2023-08-17 01:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^0[7-9][0-1]\\d{8}$')])),
                ('description', models.TextField(default='No additional description was provided.')),
                ('own_age', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('budget_min', models.IntegerField()),
                ('budget_max', models.IntegerField()),
                ('room_types', models.CharField(max_length=255, verbose_name="Types of listing you're looking for")),
                ('own_religion', models.CharField(choices=[('CHRISTIANITY', 'Christianity'), ('ISLAM', 'Islam'), ('TRADITIONAL', 'Traditional'), ('OTHER', 'Other')], max_length=255, verbose_name='Religion')),
                ('preferred_religions', models.CharField(default='', max_length=255, verbose_name='Preferred religions')),
                ('unwanted_religions', models.CharField(default='', max_length=255, verbose_name='Unwanted religions')),
                ('own_faculty', models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('AGRICULTURE', 'Agriculture'), ('ARTS', 'Arts'), ('EDM', 'Enviromental Design and Management'), ('EDUCATION', 'Education'), ('HEALTH', 'Health'), ('LAW', 'Law'), ('SCIENCE', 'Science'), ('SOCIAL SCIENCE', 'Social Science'), ('TECHNOLOGY', 'Technology')], max_length=255, verbose_name='Faculty')),
                ('preferred_faculties', models.CharField(default='', max_length=255, verbose_name='Preferred faculties')),
                ('unwanted_faculties', models.CharField(default='', max_length=255, verbose_name='Unwanted faculties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
