# Generated by Django 4.2.3 on 2023-08-16 01:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='media/profile_picture/profile_picture.png', max_length=255, null=True),
        ),
    ]
