# Generated by Django 4.2.3 on 2023-08-17 05:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='h4xrbsve4pkqkxkqsw0j', max_length=255, null=True),
        ),
    ]
