# Generated by Django 4.2.3 on 2023-08-13 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlords', '0003_alter_landlord_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Detailed description of the listing')),
                ('rent', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000, 'Rent must be at least 10000')], verbose_name='Rent per year')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Address of the listing')),
                ('type', models.CharField(choices=[('SINGLE_ROOM', 'Single Room'), ('SELF_CON', 'Self Contained'), ('ONE_BEDROOM_FLAT', 'One Bedroom Flat'), ('TWO_BEDROOMS_FLAT', 'Two Bedrooms Flat'), ('THREE_BEDROOMS_FLAT', 'Three Bedrooms Flat'), ('FOUR_BEDROOMS_FLAT', 'Four Bedrooms Flat')], max_length=255, verbose_name='Type of listing')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='landlords.landlord')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
