# Generated by Django 4.2.3 on 2023-08-14 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='likes',
            field=models.ManyToManyField(related_name='liked_listings', to=settings.AUTH_USER_MODEL, verbose_name='Users who have liked this listing'),
        ),
    ]
