# Generated by Django 4.2.3 on 2023-08-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_likes'),
        ('listings', '0002_listing_rating_listing_sum_ratings_and_more'),
    ]

    operations = [
    ]
