# Generated by Django 4.2.3 on 2023-08-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_merge_20230814_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3),
        ),
    ]
