# Generated by Django 4.2.3 on 2023-08-17 05:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='vduayichretpeiu1yg3x', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
